import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Login from "../components/Login";
import SideBar from "../components/SideBar";
import Widgets from "../components/Widgets";
import { db } from "../firebase";

export default function Home({user, posts}) {
  if (!user) return <Login />
  return (
    <div className="h-screen overflow-hidden bg-[#f0f2f5]">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main className="flex">
        {/* Sidebar */}
        <SideBar />

        {/* Feed */}
        <Feed posts={posts} />

        {/* Widgets */}
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  // get the user
  const session = await getSession(context);
  if (!session) {
    return {
      props: {}
    }
  }
  const { user } = session;

  const posts = await getDocs(collection(db, 'posts'))

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }))

  return {
    props: { user, posts: docs, },
  };
}
